server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /health {
    access_log off;
    add_header Content-Type text/plain;
    return 200 'ok';
  }

  location /api/events {
    proxy_pass http://events-service:3001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/participants {
    proxy_pass http://participants-service:3002;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/registrations {
    proxy_pass http://registrations-service:3003;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
